# Generated by Django 4.2.11 on 2024-03-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News category',
                'verbose_name_plural': 'News categories',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(help_text='Тут добавьте Тэг', max_length=30)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(help_text='Тут добавьте название статьи', max_length=100)),
                ('article_news', models.TextField()),
                ('article_image', models.FileField(upload_to='news_images')),
                ('article_author', models.CharField(help_text='ФИО автора', max_length=50)),
                ('article_created_at', models.DateTimeField(auto_now_add=True)),
                ('article_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categorymodel')),
                ('article_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.tagmodel')),
            ],
            options={
                'verbose_name': 'News article',
                'verbose_name_plural': 'News articles',
            },
        ),
    ]
